SETTINGS_CB = 'settings'
SETTINGS_TEXT = 'Настроить'
STATISTIC = 'История записей'
STATISTIC_CB = 'statistic'

YES_HURT_CB = 'yes_hurt'
YES_HURT_TEXT = 'Да, болела : ('
NO_HURT_CB = 'no_hurt'
NO_HURT_TEXT = 'Нет, не болела'
YES_PILLS_CB = 'yes_pills'
NO_PILLS_CB = 'no_pills'
YES_PILLS_TEXT = 'Да'
NO_PILLS_TEXT = 'Нет'
YES_COMMENT = 'yes_comment'
NO_COMMENT = 'no_comment'
THIS_MONTH_TEXT = 'Текущий месяц'
THIS_MONTH_CB = 'history-this_month'
LAST_MONTH_TEXT = 'Прошлый месяц'
LAST_MONTH_CB = 'history-last_month'
ALL_TIME_TEXT = 'За все время'
ALL_TIME_CB = 'history-all_time'
HISTORY = 'history-'
DETAILED_HISTORY = 'detailed-history-'
DETAILED_HISTORY_PAINFREE_TEXT = 'Дни без головной боли'
DETAILED_HISTORY_PAINFUL_TEXT = 'Дни с головной болью'
DETAILED_HISTORY_PAINFREE_CB = 'detailed-history-painfree'
DETAILED_HISTORY_PAINFUL_CB = 'detailed-history-painful'

WAITING_FOR_TIME = 'waiting_for_time'
WAITING_FOR_COMMENT = 'waiting_for_comment'

HURT_RATE = 'hurt_rate-'
PILLS = 'pills'

CB_NAME = 'headache_helper'
