WAITING_FOR_TIME = 'headache_waiting_for_time-'
WAITING_FOR_COMMENT = 'headache_waiting_for_comment-'
HURT_RATE = 'headache_hurt_rate-'
PILLS = 'headache_pills-'
COMMENT = 'headache_comment-'
LAST_DAY_TIMESTAMP = 'headache_timestamp-'
